#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
exec watchfiles --filter python --ignore-paths /app/backend/media/_projects_sources "python manage.py runserver 0.0.0.0:8000 --noreload"
