# Generated by Django 5.2.8 on 2026-04-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_alter_mutationanalysis_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mutationresult",
            name="is_equivalent",
            field=models.BooleanField(
                blank=True,
                help_text="True if Z3 + LLM classified this mutant as equivalent.",
                null=True,
            ),
        ),
    ]
