# Generated by Django 5.2.8 on 2026-04-15 09:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_mutationresult_is_equivalent"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="secret_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
