# Generated by Django 5.2.8 on 2026-04-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0009_project_secret_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="mutationanalysis",
            name="target_directory",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Base directory for the mutation analysis (e.g., 'src' or 'tinydb'). Used by frontend to scope file selection.",
                max_length=255,
            ),
        ),
    ]
